name: 'tagged-release'

on:
  push:
    tags:
      - 'v*'

jobs:
  tagged-release:
    name: 'Tagged Release'
    runs-on: 'ubuntu-latest'

    steps:
      - uses: actions/checkout@v2
      - name: Test using Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '14'
      - run: npm install
      - run: npm run gh-publish

      - uses: 'marvinpinto/action-automatic-releases@latest'
        with:
          repo_token: '${{ secrets.GITHUB_TOKEN }}'
          prerelease: true
          files: |
            LICENSE.txt
            *.dmg
            *.exe
            *.yml
